# -*- coding: utf-8 -*-
"""inicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14TnZ-V1pnTuti71m6M9OijsN5mYRUKSB
"""

#Archivo
data = pd.read_csv('/content/drive/MyDrive/ArchivosColab/Wine.csv', header=None)

# 1- Eliminar primera columna
data = data.drop(0,axis=1)
#Agregar nombres a las columnas para facilitar su uso
columns = ['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13']
data.columns = columns

# Metodo min max
new_data = data
for col in new_data.columns:
  new_data[col] = (data[col] - data[col].min()) / (data[col].max() - data[col].min())

new_data.head()